-- SmartLoad: manifests table
-- Maps to: com.smartload.entity.Manifest
-- Run against database: smartload (see application.properties)
-- Note: id is generated by the application (UUID), not by the database.
-- ADR-0011: This script is the canonical schema reference; in dev mode Hibernate ddl-auto=update
-- creates/extends the table from the entity. PostgreSQL-specific bits (JSONB) live here.

CREATE TABLE IF NOT EXISTS manifests (
    id                   VARCHAR(36)      PRIMARY KEY,
    status               VARCHAR(255)     NOT NULL,
    file_name            VARCHAR(255),
    total_pieces         INTEGER,
    total_weight_kg      DOUBLE PRECISION,
    total_volume_mm3     DOUBLE PRECISION,
    capacity_percentage  DOUBLE PRECISION,
    -- Immutable import snapshot: { "sheetName", "headers": [...], "rows": [[...], ...] }
    -- headers = Excel row 1; rows[k] = Excel row (k+2). Not returned on GET /list.
    source_grid          JSONB,
    -- Frozen at import: canonical field name → Excel column index (0-based).
    column_mapping       JSONB,
    -- Validate-time snapshot (issues, statistics, normalized packages at import). Not edited.
    validation_result    JSONB,
    created_at           TIMESTAMP        NOT NULL,
    updated_at           TIMESTAMP
);

-- Migration notes for existing databases:
--   Earlier revisions used `total_volume_cm3`. To migrate without data loss:
--     ALTER TABLE manifests RENAME COLUMN total_volume_cm3 TO total_volume_mm3;
--     UPDATE manifests SET total_volume_mm3 = total_volume_mm3 * 1000;
--   (cm³ → mm³ multiplier is ×1000 because 1 cm³ = 1000 mm³.)
--   Earlier revisions also had validation_result as `json`. To match ADR-0011 convert with:
--     ALTER TABLE manifests ALTER COLUMN validation_result TYPE jsonb USING validation_result::jsonb;
--
-- source_row_number round-trip (packages.source_row_number ↔ source_grid.rows):
--   Excel row 1 = headers (not in source_grid.rows)
--   Excel row N (N≥2) = source_grid.rows[N - 2]
--   packages.source_row_number = N for rows imported from Excel; null = synthetic/manual package.
